ClinicManagementMVC/Controllers/DoctorAppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ClinicManagement.Bussiness.ClinicBussiness;
using ClinicManagement.Bussiness.ClinicModelMV;

namespace ClinicManagementMVC.Controllers
{
    public class DoctorAppointmentController : Controller
    {
        DoctorAppointmentBussiness doctorapp = new DoctorAppointmentBussiness();
        // GET: DoctorAppointment
        public ActionResult Index()
        {
            return View(doctorapp.listofAppointment());
        }

        // GET: DoctorAppointment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DoctorAppointment/Create
        public ActionResult Create()
        {
            DoctorAppointmentsMV doctoropen = doctorapp.openFileDetalesCreate();
            return View(doctoropen);
        }

        // POST: DoctorAppointment/Create
        [HttpPost]
        public ActionResult Createnewappointment(DoctorAppointmentsMV newappintment)
        {
           






            ResponseMV result = doctorapp.createnewAppointment(newappintment);

            if (result.IsValid == true) { return RedirectToAction("Index"); }
            else
            {
                foreach (var item in result.ErrorMessages)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
                newappintment = doctorapp.openFileDetalesCreate( newappintment);
                return View("Create", newappintment);
            }
        }

        // GET: DoctorAppointment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DoctorAppointment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DoctorAppointment/Delete/5
        public ActionResult Delete(int id)
        {

          Boolean result =  doctorapp.deleteAppointment(id);
            if (result == false)
            {
                TempData["ModelName"] = "can not delete" ;
            }
            return RedirectToAction("Index");
        }

        // POST: DoctorAppointment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ClinicManagementMVC/Controllers/MedicalFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClinicManagement.Bussiness.ClinicBussiness;
using ClinicManagement.Bussiness.ClinicModelMV;

namespace ClinicManagementMVC.Controllers
{
    public class MedicalFileController : Controller
    {
        MidecalFileBussiness file = new MidecalFileBussiness();
        MedicalFileDetalisBussiness filedetailes = new MedicalFileDetalisBussiness();
        MedicalFileMeicinBussiness medical = new MedicalFileMeicinBussiness();

        public ActionResult Index()
        {

            return View(file.listofmedicalfile());
        }

     

        // GET: MedicalFile/Create
        public ActionResult Create()
        {
            MedicalFilesMV newfileopen = file.openPatientCreate();
            return View(newfileopen);
        }

        // POST: MedicalFile/Create
        [HttpPost]
        public ActionResult Createnewfile(MedicalFilesMV filenew)
            
        {
         
            ResponseMV result = file.createnewpatientmedicalfile(filenew);

            if (result.IsValid == true) { return RedirectToAction("Index"); }
            else
            {
                foreach (var item in result.ErrorMessages)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
                filenew = file.openPatientCreate(filenew);
                return View("Create", filenew);
            }

        }

        // Create new file medical for new patient
        public ActionResult CreateNewDetalies(int id)
        {
            MedicalFileDetalisMV newfileopen = filedetailes.openFileDetalesCreate();
            TempData["Fileid"]  = id;
            return View(newfileopen);
        }

        // POST: MedicalFile/Edit/5
        [HttpPost]
        public ActionResult SubmitDetalies(MedicalFileDetalisMV newdetalies)
        {
         
            newdetalies.Date = DateTime.Now ;
            newdetalies.FileID = (int) TempData["Fileid"];
            ResponseMV result = filedetailes.createnewDetails(newdetalies);

            if (result.IsValid == true) {

                return RedirectToAction("medicalFileDetailes",new { id= newdetalies.FileID });
            }
            else
            {
                foreach (var item in result.ErrorMessages)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
                newdetalies = filedetailes.openFileDetalesCreate(newdetalies);
                return View("CreateNewDetalies", newdetalies);
            }

        }


        public ActionResult  MedicinList(int id)
        {


            return View(medical.listofmedica(id));
        }



        //create medicine of the file patient
        public ActionResult Createnewmedicine(int id)
        {
            MedicalFileMedicinMV medicalopen = medical.openmedicinCreate();
            TempData["FileDetaliesid"] = id;
            return View(medicalopen);
        }

        // POST: MedicalFileMedicine/Create
        [HttpPost]
        public ActionResult submitemedicine(MedicalFileMedicinMV newmedical)
        {
            newmedical.fileDetaliesID = (int)TempData["FileDetaliesid"];
            ResponseMV result = medical.createnewpatient(newmedical);
            if (result.IsValid == true)
            {
                TempData["save"] = "save Sucess Medicien";

                return RedirectToAction("Createnewmedicine", new { id = newmedical.fileDetaliesID });
            }
            else
            {
                foreach (var item in result.ErrorMessages)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
                newmedical = medical.openmedicinCreate(newmedical);
                return View("Createnewmedicine", newmedical);
            }
        }





        //  show MedicalFile and this Details
        public ActionResult medicalFileDetailes(int id)
        {
           

            return View(file.Selectfile(id));
        }


        //  show MedicalFile  Details
        public ActionResult Details(int id)
        {
            filedetailes.listofmedicalfiledetailes(id);

            return View(filedetailes.listofmedicalfiledetailes(id));
        }


    }




}

ClinicManagementMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />
    <style>
        .navbar-inverse .navbar-nav > li > a {
            color: white;
        }
        .navbar-inverse .navbar-brand {
             color: white;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          
            <div class="navbar-header">
            
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Scripts/Medical-Heart-Logo.jpg" style="width:130px ;position:absolute;left:59px;top:5px"  />
                @Html.ActionLink("Clinic Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
              

              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="linkact">@Html.ActionLink("Patient", "Index", "Patient")</li>
                     <li class="linkact">@Html.ActionLink("Doctor", "Index", "Doctor")</li>
                    <li class="linkact">@Html.ActionLink("MedicalFiles", "Index", "MedicalFile")</li>
                    @*<li class="linkact">@Html.ActionLink("Doctors Appointment", "Index", "DoctorAppointment")</li>*@
                    <li class="linkact">@Html.ActionLink("Booking", "Index", "Booking")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
  
</body>
</html>